version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: melochord
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    cpu_period: 50000
    cpu_quota: 25000    
  
  profileservice:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: profileservice
    restart: always
    env_file: ./.env
    volumes:
      - ./server:/server  
    image: profileservice
    ports:
      - 8081:8081
    environment:
      MONGODB_URL: mongodb://mongodb:27017/melochord
    extra_hosts:
      - localhost:127.0.0.1
      - host.docker.internal:172.17.0.1      
    networks: 
      - mongobackend   
      - frontend
    cpu_period: 50000
    cpu_quota: 25000  
    
volumes:
  mongodb:
  server: 

networks:
  mongobackend:
  frontend:
    name: frontend
    external: true
